-- MySQL Script generated by MySQL Workbench
-- Thu May 27 23:34:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imobiliaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`imobiliaria` (
  `idimobiliaria` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idimobiliaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imoveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`imoveis` (
  `idimoveis` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  `imobiliaria_idimobiliaria` INT NOT NULL,
  PRIMARY KEY (`idimoveis`, `imobiliaria_idimobiliaria`),
  INDEX `fk_imoveis_imobiliaria1_idx` (`imobiliaria_idimobiliaria` ASC) VISIBLE,
  CONSTRAINT `fk_imoveis_imobiliaria1`
    FOREIGN KEY (`imobiliaria_idimobiliaria`)
    REFERENCES `mydb`.`imobiliaria` (`idimobiliaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fotos` (
  `idfotos` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NOT NULL,
  `imoveis_idimoveis` INT NOT NULL,
  PRIMARY KEY (`idfotos`),
  INDEX `fk_fotos_imoveis1_idx` (`imoveis_idimoveis` ASC) VISIBLE,
  CONSTRAINT `fk_fotos_imoveis1`
    FOREIGN KEY (`imoveis_idimoveis`)
    REFERENCES `mydb`.`imoveis` (`idimoveis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`propostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`propostas` (
  `usuario_iduser` INT NOT NULL,
  `imoveis_idimoveis` INT NOT NULL,
  `valor` DECIMAL(2) NOT NULL,
  `pagamento` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL,
  `data` VARCHAR(45) NULL,
  PRIMARY KEY (`usuario_iduser`, `imoveis_idimoveis`),
  INDEX `fk_usuario_has_imoveis_imoveis1_idx` (`imoveis_idimoveis` ASC) VISIBLE,
  INDEX `fk_usuario_has_imoveis_usuario1_idx` (`usuario_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_imoveis_usuario1`
    FOREIGN KEY (`usuario_iduser`)
    REFERENCES `mydb`.`usuario` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_imoveis_imoveis1`
    FOREIGN KEY (`imoveis_idimoveis`)
    REFERENCES `mydb`.`imoveis` (`idimoveis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
